#!/bin/bash

#THIS SCRIPT GENERATES A RANDOM PASSWORD FOR EACH USER SPECIFIED ON THE COMMANDLINE 


#DISPLAY THE FIRST POSITIONAL PARAMETER WHICH IS THE NAME OF THE SRIPT
FILENAME="${0}"
#echo "THIS PROGRAM GENERATES RANDOM PASSWORD FOR ANY GIVEN AMOUNT OF USERS ON THE COMMANDLINE."
#echo
#echo "This is the program you are executing: ${FILENAME}"

#DISPLAY THE DIRNAME AND THE BASNAME OF THE SCRIPT
#echo "This is the Dirname: $(dirname ${FILENAME}), and the Basename: $(basename ${FILENAME})."

#I WANT TO DISPLAY THE NUMBER OF ARGUMENTS THAT WAS PASSED IN TO THE SCRIPT ON THE COMMANDLINE
NUM_OF_ARGUMENTS="${#}"
echo "You passed ${NUM_OF_ARGUMENTS} arguments (parameters) to this ${FILENAME}"

echo

#MAKE SURE THE USER ENTERS AN ARGUMENT ON THE COMMANDLINE 
if [[ "${NUM_OF_ARGUMENTS}" -eq 0 ]]
then 
	#echo A REMINDER
	echo "Usage:${FILENAME} COMMANDLINE_ARG.. " >&2
	exit 1 
fi

#WE WILL GENERATE A RANDOM PASSWORD FOR THE USERS THAT WAS GIVEN ON THE COMMANDLINE 
for USER_NAME in "${@}"
do
	PASSWORD=$(date +%s%N | sha256sum | head -c12)
	echo "Name: ${USER_NAME}" "|" "Generated Password: ${PASSWORD}"
	
done

exit 0 
